### ISSUE TITLE
LSE pos坐标对象key应为dimid而非dimId

### ISSUE THREAD

**Issue by Hurry1027** [lgc-LLSEDev/NavigationAPI#1]
LSE pos坐标对象key应为dimid而非dimId，
会导致错误。
把插件内所有dimId替换为dimid后正常。

另外建议actionbar的提示修改下样式，目标位置xyz坐标只保留整数，xyz坐标颜色统一为白色。距离方块可保持保留两位小数，我觉得这样更美观。

我正在重构坐标记录插件，当初写的太草率了，不会对接插件，直接把导航api代码合并进去了，当时也是改了下才能正常用。
现在准备用quickjs的es模块写，并外部对接导航api，所以麻烦你查看问题修复一下（

**Comment by lgc2333** [comment]
divid变成divId是我故意写出来的

**Comment by Hurry1027** [comment]
> divid变成divId是我故意写出来的
嗯，刚才看明白了，虽然我不理解为什么你这样做。
这样我得重新组一下对象才行，有点不方便就是了。

**Comment by lgc2333** [comment]
理由很简单，蓝色下划线拼写错误看起来不顺眼

另外最近实在是对bds失去兴趣了，没有很多心情维护之前写的这堆插件，如果你有兴趣为这个插件贡献的话，我可以把你加进仓库的Collaborator

**Comment by lgc2333** [comment]
嗯，其实大概可能是 IntPos / FloatPos 用 JSON.stringify 序列化出来的是 `{}` 然后顺便改的名字
~~时间太久了忘掉了，也有可能只是上面那个很简单的原因~~

**Comment by Hurry1027** [comment]
> 理由很简单，蓝色下划线拼写错误看起来不顺眼
> 
> 另外最近实在是对bds失去兴趣了，没有很多心情维护之前写的这堆插件，如果你有兴趣为这个插件贡献的话，我可以把你加进仓库的Collaborator

样式修改倒是无伤大雅，
至于修改dimId为dimid不知道你的意见如何，不知道有几个插件用了这个api，如果修改可能会有兼容问题。
我一边写插件一边再测试测试吧，搞完坐标记录还需要一段时间。
到时候再考虑给导航api发个pr
